# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import logging

from langbot_plugin.api.definition.plugin import BasePlugin

logger = logging.getLogger(__name__)


class ContextStabilizer(BasePlugin):
    """上下文稳定器插件主类"""

    async def initialize(self) -> None:
        """插件启动时调用"""
        logger.info("上下文稳定器插件正在初始化...")
        
        # 验证配置
        config = self.get_config()
        
        if not config.get('audit_model_uuid'):
            logger.warning("审查模型未配置，插件功能将受限")
        
        logger.info("上下文稳定器插件初始化完成")

    def __del__(self) -> None:
        """插件终止时调用"""
        logger.info("上下文稳定器插件已停止")
